### PR TITLE
Solution to Hill Jumping Codechef Problem in C++ 

### PR DESCRIPTION
**Pull request by Kuljeet-123**
**Fixes issue:** #4608 

**Changes:**

added solution to [HILLJUMP](https://www.codechef.com/AUG17/status/HILLJUMP) in C++.

### CODE REVIEW

**Comment by arnavb** [comment]
There is overlap in this PR with your previous one I merged.

**Comment by Kuljeet-123** [comment]
@arnavb Can you please tell me how to change this PR,so that it can be merged .Please help me.

**Comment by arnavb** [comment]
@Kuljeet-123 Remake your PRs, but use _separate branches_ for everything. When switching branches, make sure to check with `git status` whether there are any extra files. Don't blindly `git add .` Explicitly add the files you are changing. I would recommend doing this all locally, not using the online Github UI.

**Comment by Kuljeet-123** [comment]
@arnavb Due to conflicts , I am closing this PR and will raise a new PR. Because I  forked the repo again

**Pull request closed without merging**
