### PR TITLE
Add stats table and script to generated the table

### PR DESCRIPTION
**Pull request by sirex**
It is not clear which algorithms are implemented in which languages, so
a table with overview of the algorithms would help to see what is
missing.

### CODE REVIEW

**Comment by arnavb** [comment]
Why don't you do it in a markdown file so that an actual table shows up? (Just a recommendation, since an actual table would be clearer than just a text one)

**Comment by AdiChat** [comment]
This is a great addition. 😄 

We need to manage all Cosmos tools well. I will merge this soon 👍

**Comment by sirex** [comment]
@arnavb my primary intention was to read this table from terminal, but the table is quite readable from web browser too: https://raw.githubusercontent.com/sirex/cosmos/stats-tool/STATS.txt

Rendering table in markdown file is probably a good idea, but I will leave it to someone else.

**Comment by arnavb** [comment]
@sirex  I guess you are right about that. I can see that it is clear enough. It was just a recommendation on my part anyway. 👍

**Comment by AdiChat** [comment]
@sirex Kindly open a pull request containing `stats.py` and `stats.txt` in [this repository](https://github.com/OpenGenus/cosmos-stat) at the root folder. I will merge it and bring in subsequent changes in the structure of the repository 👍 

For this pull request, kindly place the `stats.txt` at [.github folder](https://github.com/OpenGenus/cosmos/tree/master/.github) and remove `stats.py` 👍

**Comment by AdiChat** [comment]
Looks great 😍 

You have made a wonderful contribution. Join us [**at our community forum**](https://discourse.opengenus.org/signup) :family_man_woman_girl_boy: to get connected 
We shall take this forward in future features

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus

**Pull request merged**
