### PR TITLE
updated anagram_search.cpp

### PR DESCRIPTION
**Pull request by sainikhit2k**
**Fixes issue:**

Refactored code

**Changes:**

Used vector of size 26 instead of using a map

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks great 😍 

You have made a wonderful contribution. 
Join us [**at our community forum**](https://discourse.opengenus.org/signup) :family_man_woman_girl_boy: to get connected and access to community benefits

If you would like to [join our internship program](https://discourse.opengenus.org/t/internship-guidelines-at-opengenus/2335/) and contribute to [OpenGenus IQ](https://iq.opengenus.org/), let us know and we will be happy to have you onboard 

Hope you are enjoying your journey 🚆  with **OpenGenus**
og (29)

**Comment by sainikhit2k** [comment]
@AdiChat Hi I would to join in your internship program

**Comment by arnavb** [comment]
@sainikhit2k The place to join is [here](https://discourse.opengenus.org/t/internship-guidelines-at-opengenus/2335).

**Comment by sainikhit2k** [comment]
@arbavb Expressed my interest there. Waiting for the reply

**Comment by arnavb** [comment]
@sainikhit2k Aditya has been rather inactive lately. You will just have to wait. I cannot help you, since I just maintain this repository.

**Comment by sainikhit2k** [comment]
Okay

**Pull request merged**
