### PR TITLE
Connected Component Labelling, Contrast Enhancement Algorithms & Bayesian Belief Network

### PR DESCRIPTION
**Pull request by yashml**
**Changes:**
- In *master/code/artificial_intelligence/src/image_processing*:
             - In a  new folder */contrast_enhancement* added:  **Histogram Equalization**,  **Contrast Limited Adaptive Histogram Equalization (CLAHE)**, and **Min-Max Constrast Stretching** code for Black and White and Color Images using OpenCV. The Histograms and CDFs are also plotted to explain the code better.
             - In a  new folder */connected_component_labelling* added: Input and output shown on 3 images to explain the code better.

- In *master/code/artificial_intelligence*:  
Creation of **Bayesian Belief Network** using pgmpy and some simple queries on the network.

### CODE REVIEW

**Comment by yashml** [comment]
@arnavb do have a look. I think both Histogram Equalization and Bayesian Belief Networks are well coded. Do let me know if you think any changes need to be made.

**Comment by yashml** [comment]
@arnavb please do have a look, I have added  6 notebooks which cover 3 topics. Do let me know if you think any changes need to be made.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus

**Comment by yashml** [comment]
Thank you sir, I'm really enjoying learning and sharing what I've learned with others! 😄  I will continue to contribute to Cosmos and other projects at OpenGenus!

**Pull request merged**
