### PR TITLE
MinCoinsGreedy.java

### PR DESCRIPTION
**Pull request by vinayb21**
Greedy approach to find minimum number of coins required.

### CODE REVIEW

**Comment by AdiChat** [comment]
We, already, have an implementation in `Java`. Kindly take a look at other scopes of contribution or refactor existing code ([see](https://github.com/OpenGenus/cosmos/tree/master/code/greedy-algorithms/minimum_coins)) 👍

**Comment by vinayb21** [comment]
Okay, Thanks! 🙂

**Comment by vinayb21** [comment]
I have completed BabylonianMethod.java and removed the previous MinCoinsGreedy.java. Kindly check and pull the changes.

**Comment by AdiChat** [comment]
Babylonian method in `Java` also exists ([see](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/babylonian_method/Babylonian.java)) 👍 

Kindly take a look at other scopes of contribution or refactor existing code 👍

**Comment by vinayb21** [comment]
Solution for Check_is_square in mathematical algorithm for JAVA is uploaded. Also it does not exist already. 👍

**Comment by vinayb21** [comment]
Kindly push the changes on checking the code.

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by vinayb21** [comment]
Thanks. I am passionate about data structures and algorithms. Enjoying to
code and contribute.

**Comment by AdiChat** [comment]
Great to know 😍

**Pull request merged**
