### PR TITLE
Solution to MEETUP Codechef Problem in C++

### PR DESCRIPTION
**Pull request by Kuljeet-123**
**Fixes issue:** #4701 

**Changes:**

Added Solution to [MEETUP](https://www.codechef.com/problems/MEETUP) problem in C++.

### CODE REVIEW

**Comment by arnavb** [comment]
@Kuljeet-123 Please separate your code in all your different pull requests; they all seem to have combined.

**Comment by Kuljeet-123** [comment]
@arnavb I have updated all the PR.Please review it.

**Comment by arnavb** [comment]
@Kuljeet-123 They are al still combined, as you can see in the Files Changed tab.

**Comment by Kuljeet-123** [comment]
@arnavb Do I have to update all the files.

**Comment by Kuljeet-123** [comment]
@arnavb I have updated all the files .Please review it and merge it.

**Pull request merged**
