### PR TITLE
Add a CDCL SAT Solver

### PR DESCRIPTION
**Pull request by togatoga**
Add a CDCL SAT Solver written by c++(https://github.com/togatoga/togasat)
If there is any problems about submodule commit, I re-created the pull request(adding only sat solver code).

### CODE REVIEW

**Comment by arnavb** [comment]
Why?

**Comment by togatoga** [comment]
@arnavb 
My commit is first to add submodule.
I'm worry about whether this commit is inappropriate.

**Comment by AdiChat** [comment]
@togatoga It would be great if you could add the sat solver code instead of setting up a submodule. It will be good to merge then 👍

**Comment by togatoga** [comment]
@AdiChat 
I fixed commit to add the sat solver code.
🙏

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
