### PR TITLE
Create number of trailing zeros in factorials

### PR DESCRIPTION
**Pull request by 007akk**

### CODE REVIEW

**Comment by 007akk** [comment]
oh thanks for pointing out that , i am updating the same !

**Comment by AdiChat** [comment]
Kindly correct your code by considering [this `C++` code](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/count_trailing_zeroes/count_trailing_zeros_factorial.cpp) 👍 

It will be good to merge then 👍

**Comment by 007akk** [comment]
@AdiChat  i have done the required changes

**Comment by mor11235** [comment]
How can I add my code in order to pull request?

**Comment by AdiChat** [comment]
`C++` implementation exists. Kindly modify it to `C` code 👍

**Comment by mor11235** [comment]
How can I pull request on this code?

**Comment by arnavb** [comment]
@AdiChat please close this!

**Pull request closed without merging**
