### PR TITLE
Improved documentation.

### PR DESCRIPTION
**Pull request by sinAshish**

### CODE REVIEW

**Comment by sinAshish** [comment]
Close #1201 .

**Comment by AdiChat** [comment]
Changes in `readme` are currently restricted 👍

**Comment by sinAshish** [comment]
but mine was very helpful for the users 😞 .

**Comment by arnavb** [comment]
@AdiChat Are changes in nested READMEs allowed? Such as those that I'm doing in PR #1095

**Comment by matthewcurry** [comment]
Links in the readme to the repo prevents folks from hosting forks easily, as they would have to change the readme to point to their repo. Adding those links is probably not a good idea from an open source community standpoint.

**Comment by arnavb** [comment]
@matthewcurry Oh, I thought AdiChat meant like just READMEs in general. Phew!

**Pull request closed without merging**
