### PR TITLE
Add c++11 quicksort

### PR DESCRIPTION
**Pull request by M3rs**

### CODE REVIEW

**Comment by AdiChat** [comment]
Quick sort has already been pushed. Kindly take a look at other issues or refactor the existing code ([see](https://github.com/OpenGenus/cosmos/blob/master/code/sorting/quick_sort/quick_sort.cpp))

**Comment by endiliey** [comment]
Sorry. I pushed the quick sort implementation along with heap sort :)

**Comment by AdiChat** [comment]
No problem 👍

**Comment by M3rs** [comment]
Ok - I will refactor the existing implication to use iterators, thanks!

**Comment by M3rs** [comment]
Ok - updated pull request: refactored to use iterators

**Comment by AdiChat** [comment]
Add the _OpenGenus_ comment as depicted in the [contributing guideline](https://github.com/OpenGenus/cosmos/wiki/contribute)

Kindly make the above changes.

**Comment by M3rs** [comment]
Added

**Comment by AdiChat** [comment]
This commit holds 9 files but the comment has been added to only 1 file.

Kindly take a look into it.

**Comment by AdiChat** [comment]
Closing this for no update in ten days 👍 

You can always open another pull request 👍

**Pull request closed without merging**
