### PR TITLE
Create biggest_Of_N_Numbers.c

### PR DESCRIPTION
**Pull request by Vaibhav1671998**
**Changes:**
[Added new folder]
It contains code for getting biggest of n numbers that are entered by user .

### CODE REVIEW

**Comment by Vaibhav1671998** [comment]
How can i upload the code again ?

**Comment by Vaibhav1671998** [comment]
@arnavb Now check that is it fine now Or what else i had to do ?

**Comment by arnavb** [comment]
👍

**Comment by Vaibhav1671998** [comment]
When it will get Merge ?

**Comment by arnavb** [comment]
Wait for @AdiChat.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by Vaibhav1671998** [comment]
Yeah I'm enjoying my time here . How can I contribute more ?

**Comment by arnavb** [comment]
Keep adding PRs!

**Comment by Vaibhav1671998** [comment]
Ok thanxx

**Pull request merged**
