### PR TITLE
Added code for STFOOD in java

### PR DESCRIPTION
**Pull request by raksha009**
**Fixes issue:** #4534 
Code added for "Chef and Street food "problem in java

@AdiChat plz review

### CODE REVIEW

**Comment by raksha009** [comment]
@arnavb  Plz review the PR.

**Comment by arnavb** [comment]
Reformatted code:

```java
import java.io.*;
import java.util.*;

class Stfood {
    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);
        int t = s.nextInt();
        while (t-- > 0) {
            int n = s.nextInt();
            int maxprofit = 0;

            for (int i = 0; i < n; i++) {
                int stores = s.nextInt();
                int p = s.nextInt();
                int v = s.nextInt();
                int profit = (p / (stores + 1)) * v;
	       
                // updating maxprofit
                if (maxprofit < profit) {
                    maxprofit = profit;
                }
            }

            System.out.println(maxprofit);
        }
    }
}

/*
TEST CASES

INPUT
2
3
4 6 8
2 6 6
1 4 3
1
7 7 4

OUTPUT
12
0
*/
```

**Comment by raksha009** [comment]
@arnavb done the changes. Thanks

**Comment by raksha009** [comment]
Plz suggest online formatter to reformat my code.

**Comment by arnavb** [comment]
@raksha009 I didn't use an online formatter, I used the formatter in [IntelliJ IDEA](https://www.jetbrains.com/idea/). This is a very good free IDE for Java (the ultimate edition is also free for students) and its default formatter is very good.  It is also much faster than Eclipse. Consider using this!

**Comment by raksha009** [comment]
Okk thanks

**Pull request merged**
