### PR TITLE
Added fibonacci implementation in JS

### LINKED ISSUE #4364: Fibonacci in JS.
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Adding the Fibonacci number implementation in JS.

### PR DESCRIPTION
**Pull request by JanaSabuj**
**Fixes issue:**
Fixes #4364 

**Changes:**
Added fibonacci.js

### CODE REVIEW

**Comment by JanaSabuj** [comment]
@AdiChat please do review it.

**Comment by arnavb** [comment]
@JanaSabuj I'm sorry I missed this PR. I will merge it in once you reformat the file with prettier.

**Comment by JanaSabuj** [comment]
Okay. Will do it right now.

**Comment by JanaSabuj** [comment]
@arnavb Prettified the code in JS.

**Pull request merged**
