### PR TITLE
Add index for coding style

### PR DESCRIPTION
**Pull request by iattempt**
**Fixes issue:**

**Changes:**
1. add index for coding style of c/java/kotlin/python

### CODE REVIEW

**Comment by arnavb** [comment]
Is this currently WIP?

**Comment by iattempt** [comment]
done.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by iattempt** [comment]
refer to #3053

**Pull request merged**
