### PR TITLE
Plaindrome check using javascript

### PR DESCRIPTION
**Pull request by amitsin6h**
@AdiChat merge it

### CODE REVIEW

**Comment by AdiChat** [comment]
Your `Python` solution is incorporated in @arnavb 's code. Kindly remove it. I will merge the `JavaScript` code 👍

**Comment by amitsin6h** [comment]
@AdiChat merge it

**Comment by AdiChat** [comment]
Looks great 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by amitsin6h** [comment]
@AdiChat You still hope keep checking my PR and Code :p

**Comment by AdiChat** [comment]
I am sure you love ❤️ cosmos 😆

**Comment by amitsin6h** [comment]
@AdiChat yeah btw your fb id

**Pull request merged**
