### PR TITLE
Add pangram checker in PHP

### PR DESCRIPTION
**Pull request by mfrancis95**

### CODE REVIEW

**Comment by mfrancis95** [comment]
The PHP Style Guide says to omit the ending ?> tag when the code is all PHP.

**Comment by arnavb** [comment]
I know, I realized this a few days ago, just forget what I said! (So hypocritical of me!)

**Comment by mfrancis95** [comment]
That's fine. Are there any other style corrections that I'm missing?

**Comment by arnavb** [comment]
No, its good!

**Comment by mfrancis95** [comment]
Okay, then it should be good to merge.

**Comment by arnavb** [comment]
Yes, but I do not have that power, @AdiChat does.

**Comment by mfrancis95** [comment]
@AdiChat, please merge.

**Comment by AdiChat** [comment]
Looks great 😍 

Somehow, I overlooked this. 😓 
Hope you are enjoying your journey 🚆  with **OpenGenus** 👍

**Comment by AdiChat** [comment]
There are two copies of `pangram_checker.php`. Please remove the one not in the `src` folder. 
Showhow, I overlooked this 😓 

It will be good to be merged then 👍

**Comment by mfrancis95** [comment]
My bad. It's all set now.

**Comment by AdiChat** [comment]
No problem. Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
