### PR TITLE
Adding insertion operations in singly linked lists for python

### PR DESCRIPTION
**Pull request by uds5501**
**Fixes issue:**
Adding Operations on Data Structures in Different Languages #3592 

It is the first instalment of python operations for singly linked list insertions as discussed in that particular issue comments

**Changes:**

New files added in:
list/Singly-linked-list/Operations for insertions in `front`,`end` and `after the nth node`

### CODE REVIEW

**Comment by uds5501** [comment]
@AdiChat It would be great if you could review this PR!

**Comment by uds5501** [comment]
@arnavb I made sure to follow the style guide, as for file name situation, I will fix it right now. Thank you for guidance !

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus_first

**Comment by Nivig1310** [comment]
Hello, is there anything I can add to this? Any method you would like implemented? Please let me know!

**Pull request merged**
