### PR TITLE
Added number recogniser

### PR DESCRIPTION
**Pull request by ddalgi29**
Neural network which can recognise numbers, with a data set included to train :)

**Fixes issue:**

#6317 

**Changes:**

Added a neural network which can be trained to recognise numbers in "artifical_intelligence" with dataset to train it :D

### CODE REVIEW

**Review by walidbarakat — CHANGES_REQUESTED** [review]
you can include all of the files in one folder since they're all related to each other?

**Comment by ddalgi29** [comment]
> you can include all of the files in one folder since they're all related to each other?

They are all in the same folder afaik

**Comment by ddalgi29** [comment]
All of them are contained here

**Comment by walidbarakat** [comment]
sorry for not being more specific, but  "number recogniser" can be implemented in some rust, C++ or java. can you please make a subfolder for the sake of only-python-implemented-number-recogniser?

**Comment by ddalgi29** [comment]
> sorry for not being more specific, but "number recogniser" can be implemented in some rust, C++ or java. can you please make a subfolder for the sake of only-python-implemented-number-recogniser?

No problem :D I understand now, I made the changes!

**Review by AdiChat — APPROVED** [review]

**Comment by AdiChat** [comment]
Looks great 😍 

Thank you for your contribution.

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
