### PR TITLE
Find Height of BST in C

### PR DESCRIPTION
**Pull request by aasthasona79**

### CODE REVIEW

**Comment by AdiChat** [comment]
Kindly remove the executable code `a.out` 👍 

It will be good to add then 👍

**Comment by rstalekar** [comment]
Ok I will do it in C++

**Comment by rstalekar** [comment]
Can I also write code on AVL tree i.e. Balanced Binary Tree in C?

**Comment by AdiChat** [comment]
Sure. @rstalekar Go for it 👍

**Comment by rstalekar** [comment]
Meanwhile the code written in cpp is actually C code, can  you please rename it Aastha from Binary_Search_ Tree_Height_Max_Depth.cpp to Binary_Search_ Tree_Height_Max_Depth.c

**Comment by aasthasona79** [comment]
@AdiChat Done! I have removed the executable file.

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by rstalekar** [comment]
Done with my C++ code of finding the heiight of the BST. Will upload in short time

**Pull request merged**
