### PR TITLE
update singly_linked_list.cpp to use all features of cpp.

### PR DESCRIPTION
**Pull request by dparikh85**
Use of classes can be done rather than still using struct.

**Changes:**
Classes are used rather than struct and "using namespace std" is added.

### CODE REVIEW

**Comment by InfiniteCoder** [comment]
It's good idea to use classes.
But using `using namespace std` is not recommended. Read [this post on SO](https://stackoverflow.com/q/1452721)

**Comment by dparikh85** [comment]
Okay  Thanks.

‌

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by dparikh85** [comment]
Yes☺️

**Pull request merged**
