### PR TITLE
rearrange folders

### PR DESCRIPTION
**Pull request by iattempt**
**Fixes issue:**
#3107 

**Changes:**
1. rearrange data structures: based on [wiki-page](https://en.wikipedia.org/wiki/List_of_data_structures)
2. separated in src. and test folders

done.

### CODE REVIEW

**Comment by arnavb** [comment]
The only thing I want to say is to _not_ use special characters such as parentheses in your file/folder names, since this may confuse some software and filesystems.

**Comment by iattempt** [comment]
Udpated.

**Comment by iattempt** [comment]
merge master

**Comment by iattempt** [comment]
merge master ce31248

**Comment by iattempt** [comment]
52 new line is README.md files

**Comment by arnavb** [comment]
Did you do a rebase?

**Comment by iattempt** [comment]
I did, for multiple times. why are you asking this way?

**Comment by arnavb** [comment]
Just curiosity. 😆

**Comment by AdiChat** [comment]
No problem. Do not worry. 😃 

There are a few conflicts. Just resolve them and I will merge this instantly before other pull requests.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
