### PR TITLE
Fixed Signed/Unsigned Mismatch Warnings that were Causing Travis CI warnings

### PR DESCRIPTION
**Pull request by arnavb**
**Fixes issue:** N/A

**Changes:**
- Fixed Signed/Unsigned Mismatch Warnings that were Causing Travis CI warnings
- I didn't account for best coding practices, I just fixed the comparisons.

### CODE REVIEW

**Comment by arnavb** [comment]
@iattempt, I was basically doing a `git fetch upstream && git merge upstream/master --no-edit` directly through Github. So for this I had to merge from this repository into my fork. PR #12 is actually PR #12 from _my_ repository, which was used to merge all the latest commits into my fork.

**TL;DR**: I was too lazy to open up my ide and run the commands above, so I did it from Github. 😂

**Comment by arnavb** [comment]
@AdiChat please merge!

**Comment by arnavb** [comment]
@AdiChat please merge!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
