### PR TITLE
Added spiral print of 2d array in python

### PR DESCRIPTION
**Pull request by sudhanshuchopra**
Added code in python
Added guiding comments

### CODE REVIEW

**Comment by AdiChat** [comment]
need to change the spaces in folder name to underscore `_`.

Kindly add the header comment as depicted in the [Contribution guidelines](https://github.com/OpenGenus/cosmos/wiki/contribute)

**Comment by sudhanshuchopra** [comment]
Ok thanks for the help

**Comment by sudhanshuchopra** [comment]
@AdiChat added the required header and changed the name of the folder

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
