### PR TITLE
Added comb_sort algo in python

### PR DESCRIPTION
**Pull request by parulagg27**
**Fixes** #2720 

**Changes:**
Added comb sort algorithm code in python

### CODE REVIEW

**Comment by parulagg27** [comment]
Do I need to make any changes in this PR, @AdiChat ?

**Comment by AdiChat** [comment]
The code looks good. You just need to move it to the correct folder (`code/sorting/src/comb_sort/`). Kindly make the change and it will be good to be merged. :+1:

**Comment by parulagg27** [comment]
Made the required changes @AdiChat :smiley:

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
