### PR TITLE
Converting every 0 as  input digit to 5

### PR DESCRIPTION
**Pull request by shubhamverma1997**

### CODE REVIEW

**Comment by AdiChat** [comment]
This code already exists in `C++` ([see](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/replace_0_with_5/replace.cpp)) 👍 

Kindly take a look at other scopes of contribution or refactor existing code 👍

**Comment by shubhamverma1997** [comment]
I posted this because it is more memory efficient and fast . Just wanted to improve the quality :)

**Comment by shubhamverma1997** [comment]
@AdiChat can i modify the existing one ?

**Comment by AdiChat** [comment]
Yes. I see I will add this one as efficient. Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by shubhamverma1997** [comment]
Thankyou

**Pull request merged**
