### PR TITLE
Addresses #41: Added Quick-Sort algorithm in Go language

### PR DESCRIPTION
**Pull request by harshit98**
This PR addresses issue #41.

- Added Quick-Sort algorithm in Go language. :+1:

### CODE REVIEW

**Comment by AdiChat** [comment]
Add the _OpenGenus_ comment as depicted in the [contributing guideline](https://github.com/OpenGenus/cosmos/wiki/contribute)

**Comment by harshit98** [comment]
@AdiChat Done. 😄

**Comment by harshit98** [comment]
@AdiChat Please review the pull request.

**Comment by AdiChat** [comment]
Quick sort in `Go` exists.

Closing this  👍 
You can always open another pull request 👍

**Pull request closed without merging**
