### PR TITLE
Added binary to int in Python

### LINKED ISSUE #2417: Add binary to integer in Python
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Code for integer to binary conversion in Python is available. However, binary to integer in Python isn't available.

### PR DESCRIPTION
**Pull request by janakrajchadha**
**Fixes issue:** Fixes #2417

**Changes:**
Added python method to convert a binary number (string format) to an integer.

### CODE REVIEW

**Comment by arnavb** [comment]
You need to revert the second change here. (Use `git revert <commit-hash>`

**Comment by janakrajchadha** [comment]
@arnavb Ah, I don't know how I missed that.

**Comment by janakrajchadha** [comment]
@arnavb Did I miss something here? 😅

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by arnavb** [comment]
@janakrajchadha It was just a recommendation, don't worry!

**Pull request merged**
