### PR TITLE
Merged all Style Guides into style_guide.md

### PR DESCRIPTION
**Pull request by arnavb**
**Resolves issue:** #2984

**Changes:**
- Moved all of the style guides to README.md
- Renamed all of these new files to style.md

### CODE REVIEW

**Comment by arnavb** [comment]
@AdiChat should I call these files README.md, or style.md, I'm not sure.

**Comment by AdiChat** [comment]
`readme`s are more visible, so, this should be named as `readme` or a `readme` with some information should be placed at each language directory.

**Comment by arnavb** [comment]
@AdiChat done.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
