### PR TITLE
Binomial Coefficient in JS and Fibonacci Search in C

### PR DESCRIPTION
**Pull request by nipunbharti**
**Fixes issue:** #Binomial Coefficient implementation in JavaScript

**Changes:**
Added binomial_coefficient.js

### CODE REVIEW

**Comment by nipunbharti** [comment]
Fixes Issue: #Fibonacci Search in C implemented

Changes:
Added fibonacci_search.c

**Comment by AdiChat** [comment]
Kindly remove the binary files ` .DS_Store`

**Comment by nipunbharti** [comment]
Done

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by nipunbharti** [comment]
Thank you so much. I love what you guys are doing here 😄

**Pull request merged**
