### PR TITLE
Add Amicable Numbers for Rust

### PR DESCRIPTION
**Pull request by dowoncha**
#1991

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Comment by AKTEwMmcnWnPjbT** [comment]
fucking nigger

**Pull request merged**
