### PR TITLE
some programs added and modified

### PR DESCRIPTION
**Pull request by tbhaxor**
as @arnavb  told me to commit everything in one branch in [this](https://github.com/OpenGenus/cosmos/pull/3012) PR

### CODE REVIEW

**Comment by tbhaxor** [comment]
@arnavb  i mailed something to you on  `arnavborborah11@gmail.com`, plz check it and reply asap

**Comment by tbhaxor** [comment]
@AdiChat

**Comment by tbhaxor** [comment]
@arnavb  will u hlp me in resolving this conflicts plz 😕

**Comment by arnavb** [comment]
Its a pretty easy conflict. (Fetch the commits from this repo through an upstream link), and merge it. Then the merge conflicts should fix themselves. The reason you have a conflict is because the folder mathematical-algorithms was renamed to mathematical_algorithms.

**Comment by arnavb** [comment]
I suggest you follow these steps (if you already have an upstream repo, skip 1 - 5)

1. `git remote add upstream https://github.com/OpenGenus/cosmos.git`
2. `git fetch upstream && git merge upstream/master --no-edit`
3. If you get a merge conflict here, open replace_0_with_5.py
4. Read https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by tbhaxor** [comment]
@arnavb  bro  😕

**Comment by arnavb** [comment]
Now you have the problems, since I renamed the folders to mathematical_algorithms, not mathematical-algorithms. (Same with string-algorithms).

**Comment by arnavb** [comment]
Oh ya, why are you modifying 759 files?

**Comment by tbhaxor** [comment]
@arnavb  i hv just renamed some directories

**Comment by arnavb** [comment]
Did you follow the steps I said before?

**Comment by tbhaxor** [comment]
@arnavb  plz check now

**Comment by arnavb** [comment]
Good, no more merge conflicts. 👍

**Comment by tbhaxor** [comment]
it was like are bhai bhai bhai :P

**Comment by arnavb** [comment]
😆

**Comment by arnavb** [comment]
@AdiChat

**Comment by AdiChat** [comment]
Kindly remove `morsecode.go`, `morsecode.py` and `morsecode.js` as they already exist. The existing folder name is `morse_code` while it is `morse-code` in this pull request, so, it did not appear as a conflict and will create a duplicate copy. It will be good to merge after this minor change 👍

**Comment by tbhaxor** [comment]
@AdiChat deleted all files with morse-code.*

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
