### PR TITLE
Fixes #390

### LINKED ISSUE #390: Adding [ contributing.md ] as [ .github/CONTRIBUTING.md ]
@AdiChat I would like to work on this issue ! Please add hacktoberfest label.

### PR DESCRIPTION
**Pull request by bhaveshAn**
@AdiChat 
This PR fixes #390 , kindly merge this, Thanks

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by bhaveshAn** [comment]
> Hope you are enjoying your journey with OpenGenus

@AdiChat Yeah

**Comment by bhaveshAn** [comment]
@AdiChat please check https://github.com/OpenGenus/vidsum/pull/30 and https://github.com/OpenGenus/vidsum/pull/29

**Comment by AdiChat** [comment]
Reviewed 👍

**Pull request merged**
