### PR TITLE
Created Quick select in python #4603

### PR DESCRIPTION
**Pull request by aryangulati**
**Fixes issue:**

Created Quick select in python #4603

**Changes:**

Added Quick select in python #4603
code/sorting/src/quickselect.py

### CODE REVIEW

**Comment by arnavb** [comment]
Same issues as your other PRs.

**Comment by arnavb** [comment]
@aryangulati You don't necessarily have to close your PRs. Just rewrite the algorithm, but do it yourself.

**Comment by aryangulati** [comment]
okayy

**Comment by aryangulati** [comment]
but how ?

**Comment by arnavb** [comment]
@aryangulati First, get a proper understanding of how to use [git](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) (those videos might seem long, but they are helpful). Then recreate a PR, using the geeksforgeeks article as guidance.

**Comment by aryangulati** [comment]
No i am saying that see their is no need of this issue AS ITS ALREADY CREATED IN  OPENGENUS ALL THREE ISSUES

**Comment by aryangulati** [comment]
https://github.com/OpenGenus/cosmos/tree/master/code/selection_algorithms/src

**Comment by arnavb** [comment]
Huh. Thanks for clarifying. I was only looking in the directory you submitted this PR in.

**Comment by aryangulati** [comment]
SO PLS REMOVE THE LABEL THEN WILL TAKE CARE IN FUTURE

**Comment by aryangulati** [comment]
ARE U REMOVING THE LABEL ??

**Comment by aryangulati** [comment]
@arnavb ???

**Comment by aryangulati** [comment]
Hey please reply??

**Comment by arnavb** [comment]
@aryangulati Please do not spam the comments and do not use all caps. It is unnecessarily rude. I will remove the label for now but take care in the future.

**Pull request closed without merging**
