### PR TITLE
Merged "language" and "languages" folders into "languages" folder

### PR DESCRIPTION
**Pull request by khuang0312**
Addresses Issue #4803:
Language and Languages folder can be combined to Languages folder

Merged "language" and "languages" folders into "languages" folder

### CODE REVIEW

**Comment by arnavb** [comment]
@khuang0312 You didn't move the code from the removed folder to languages.

**Comment by khuang0312** [comment]
The language folder in the current revision of the repository contains c/loop and cpp/loop. If you check the languages folder in my fork, it contains c/loop and cpp/loop.

**Comment by khuang0312** [comment]
I just made a commit to my fork that should have readded the code from the removed folder to languages.

**Comment by arnavb** [comment]
Nice job! Sorry for the late response, I get a lot of notifications, I probably just missed yours.

**Pull request merged**
