### PR TITLE
Updated atbash cipher code in Python.

### PR DESCRIPTION
**Pull request by shlokgilda**
**Changes:**
1. Simplifies the code by using inbuilt Python functions.

### CODE REVIEW

**Comment by shlokgilda** [comment]
@arnavb Could you please review the PR?

**Comment by shlokgilda** [comment]
@arnavb Made the necessary changes.

**Comment by shlokgilda** [comment]
@arnavb Could you please merge this request if everything seems fine?

**Comment by arnavb** [comment]
@shlokgilda I am unable to merge; wait for @AdiChat.

**Comment by shlokgilda** [comment]
@arnavb All right! Thanks a ton! :)

**Comment by arnavb** [comment]
@shlokgilda I've recently become a maintainer of cosmos so I should have merge rights. However, there are some changes I need you to implement.

1. Move the function docstring inside the function and use the typical docstring format:
    ```python
    """text
    more
    text
    """
2. Run [black](https://github.com/ambv/black) on your code to autoformat it. Check the Travis CI build for any errors in the Python 3.6 job related specifically for _your_ file.

**Comment by shlokgilda** [comment]
@arnavb I have made the necessary changes in my code file which pertains to this PR.

I have found a few errors in many other Python files which I would be fixing in another PR. If you want, I can make the changes in the current PR itself. 

Please do let me know your opinions.

**Comment by arnavb** [comment]
Please do those changes in a separate PR.

**Comment by arnavb** [comment]
djldk 3

**Pull request merged**
