### PR TITLE
Fix for issue #6452  add print_left_child_elements.cpp

### PR DESCRIPTION
**Pull request by awdhesh-kumar27**
add print_left_child_elements.cpp

**Fixes issue:**

6445

**Changes:**

Code added

### CODE REVIEW

**Comment by awdhesh-kumar27** [comment]
Please accept the PR with hactoberfest-accepted label.

**Comment by awdhesh-kumar27** [comment]
> Place in correct location
I placed in Binary Tree Folder. 
If I am wrong then please suggest the correct path

**Comment by AdiChat** [comment]
Place in "code/data_structures/src/tree/binary_tree/binary_tree/print_left_child/code.cpp"

**Comment by awdhesh-kumar27** [comment]
Now path is changed. Accept the PR with hacktoberfest label.

**Comment by awdhesh-kumar27** [comment]
> Place in "code/data_structures/src/tree/binary_tree/binary_tree/print_left_child/code.cpp"

Path is updated please  accept the PR with hacktoberfest label

**Comment by awdhesh-kumar27** [comment]
Kindly accept the PR with hacktoberfest label.  Path is already updated

**Pull request closed without merging**
