### PR TITLE
Added: factorial.cpp in DP

### PR DESCRIPTION
**Pull request by YashovardhanSiramdas**
**Changes:**
Added factorial.cpp in Dynamic Programming.

### CODE REVIEW

**Comment by mansiag** [comment]
@YashovardhanSiramdas This is the recursive implementation of factorial.cpp, not a Dynamic Programming implementation. Update your code to follow dp approach.

**Comment by YashovardhanSiramdas** [comment]
@mansiag Referred some online resources and got to know that DP has to use either tabulation or memoization. Thanks for pointing out ! :smiley: 

Closing this PR. #3465 does the DP implementation of factorial.

**Comment by mansiag** [comment]
Yeah

**Comment by mansiag** [comment]
@YashovardhanSiramdas You are welcome.:smile:

**Pull request closed without merging**
