### PR TITLE
Create reverse_queue.py

### PR DESCRIPTION
**Pull request by Z-Fikar**
#706 

Reverse Queue created in Python Language.

Actually I do not want to work twice as creating a new Queue class, considering Queue in Python has been created [here](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/queue/queue/queue.py). I prefer to import it and give a link to it in my code, like this one #1206

But there are some differences with what I know and what I want, and those will affect my code. Such as:
+ The data entered can only be in integer data type
+ dequeue() method removes the first element and returning its value, which should not.
+ No method for front() and size()
+ Attributes can still be accessed from outside the class

But still, I have some doubt. 
- The size method() returns whether the current queue size or queue's max size.
- I don't know whether I should make the `max` variable to be private or public.

In the end, I make size() for returning the current queue size, and `max` to be private because I didn't use it outside the class.

### CODE REVIEW

**Comment by arnavb** [comment]
The `size` method is actually really useful; you should keep it for the _current_ size. For the max size, consider creating a function `capacity`. The C++ STL does this for its containers as public member functions.

**Comment by Z-Fikar** [comment]
Yeah, it is true. But it is not like my `Queue` class will be used for something else. <br/>
If someone want to know the algorithm behind `Queue`, they will go to [code/data_structures/queue/queue](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/queue/queue) not to [code/data_structures/queue/reverse_queue](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/queue/reverse_queue), that is how this repo works right? at least for me.

**Comment by arnavb** [comment]
@Z-Fikar sure, I guess. Don't be negative ;). Maybe your code will be very famous!

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
