### PR TITLE
Makes factorial an Int extension and added tests

### PR DESCRIPTION
**Pull request by FrankKair**
**Fixes issue:**
No particular issue.

**Changes:**
Adds `factorial()` as a function of the Int struct and adds some tests.

### CODE REVIEW

**Comment by FrankKair** [comment]
@arnavb I have checked the style guide and the code seems to be compliant.
Have you found any issue? Maybe I missed something?

**Comment by arnavb** [comment]
@FrankKair No, it was just a reminder, that's all!

**Comment by FrankKair** [comment]
@arnavb Nice! :)

**Comment by FrankKair** [comment]
@arnavb Is this ready to go?

**Comment by arnavb** [comment]
@FrankKair Yup, just wait until @AdiChat merges this!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
