### PR TITLE
Add Newton-Raphson C++ example and fix compilation error in C example

### PR DESCRIPTION
**Pull request by ulvgard**
Adding a C++ example for Newton-Raphson iteration. Also, atttempts to fix compilation error using Clang 4.0.0 in C example.

### CODE REVIEW

**Comment by ulvgard** [comment]
@mor11235 What code is that?

**Comment by mor11235** [comment]
I think I can implement the algorithm in c++. Is it needed?

**Comment by ulvgard** [comment]
@mor11235 This pull-request does exactly that. You can view my contribution by clicking the commit `
1585810` above. Of course, I always appreciate your comments on this C++ example in particular. 

I do not know if the maintainers want or allow multiple contributions? I think multiple examples can have a purpose if they solve each add some interesting aspect of C++. In any case, you can always contribute by adding an example in another language.

**Comment by mor11235** [comment]
1585810

**Comment by AdiChat** [comment]
@mor11235 : As pointed out by @ulvgard, multiple contributions in the same language are allowed only when they reflect different ideas 👍

**Comment by AdiChat** [comment]
@ulvgard Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
