### PR TITLE
Circular Linked List Java

### PR DESCRIPTION
**Pull request by rcopstein**
Created a circular linked list example in Java based on the C++ one

### CODE REVIEW

**Comment by arnavb** [comment]
Just a recommendation, you could consider actually making a linked list class, with member functions, because right now there is nothing unique in your class that is not there in any other linked list class. Only the main function is different.

**Comment by rcopstein** [comment]
@arnavb Ok, that does sound better. I wondered if the idea was for me to create a whole new example or just port the one they already had.

I'll do that and re-attempt the pull request.

Thanks ;)

**Comment by rcopstein** [comment]
I did as @arnavb asked and changed my code to be a class with proper methods. Thanks again 👍

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
