### PR TITLE
Added order parameter to Selection sort, added comments

### PR DESCRIPTION
**Pull request by siddhantbarua**
**Fixes issue:**
Specify ascending/descending property for comparison based sorts #5881

**Changes:**
Added an 'order' parameter to the Selection Sort algorithm, so users can
sort in Ascending or Descending Order. Also added comments, and split
the code up into separate functions.

**Language:**
C

### CODE REVIEW

**Review by Devansh-Maurya — CHANGES_REQUESTED** [review]
Please write function name and return type on the same line.

**Comment by siddhantbarua** [comment]
> Please write function name and return type on the same line.

@Devansh-Maurya Does this mean the C style guide is out of date? The style guide instructed that I write the type on a separate line.

**Review by Devansh-Maurya — APPROVED** [review]
Yeah. It's all good as long as it obeys the style guide. Sorry for missing that.

**Review by AdiChat — APPROVED** [review]

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus

**Pull request merged**
