### PR TITLE
Add Python code and readme in ISODATA and DBSCAN clustering algorithm

### PR DESCRIPTION
**Pull request by gaoliyao**
**Fixes issue:**

**Changes:**

### CODE REVIEW

**Comment by gaoliyao** [comment]
This is my first PR. Please review my work and tell me if I correctly followed the contribution guidelines.

**Comment by AdiChat** [comment]
As per the convention we follow, folder names `DBSCAN Clustering` and `ISODATA Clustering` must be changed to `DBSCAN_clustering` and `ISODATA_clustering` respectively. 

You may take a look at our [python style guide](https://github.com/OpenGenus/cosmos/blob/master/guides/coding_style/python/README.md).

The code with associated note looks great. 😄 Kindly make the naming changes and it will be good to be merged 👍

**Comment by AdiChat** [comment]
Kindly remove the binary files `.DS_Store` There are 3 such files associated with this pull request 👍 

Additionally, you seemed to have removed the author information in the comments you earlier added. In fact, we encourage mentioning sources, original authors and edits in comments to better reflect credit. You may consider adding them back if you like. 

Concerned comment:
```
# author: choffstein
# https://github.com/choffstein/dbscan/blob/master/dbscan/dbscan.py
# revised by Mars
```

Kindly make the changes and we will merge it immediately 👍

**Comment by gaoliyao** [comment]
Hi, I may be able to revise it tomorrow. Please review it again next Monday. Thanks!

**Comment by AdiChat** [comment]
Sure. Do it at your convenience. 👍

**Comment by gaoliyao** [comment]
Hi, I revised the work again. Please review it. Thanks!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
