### PR TITLE
Travis: build support for both C and C++, using gcc and clang compilers

### PR DESCRIPTION
**Pull request by InfiniteCoder**
**Fixes issue:** Now both C and C++ are supported, for both gcc and clang compiler

**Changes:**
changed travis.yml to use matrix. Just add new languages following the same format,
changed makefile to add C++ compilation.

### CODE REVIEW

**Comment by arnavb** [comment]
You opened another PR?

**Comment by InfiniteCoder** [comment]
@arnavb I thought it'd be better to push everything now, rather than waiting for something to cause merge conflict. I don't know why the PR won't add into the last one. So I created new one. The old one could be accepted or rejected, it shouldn't make a difference(I guess).

**Comment by arnavb** [comment]
You should probably close the old one, then.

**Comment by AdiChat** [comment]
Kindly remove `n_queen.c` and `Exponentation_power.c` and include them in separate pull requests and remove the travis batch from readme as well. We will add the batch later. 

It will be good to be merged 👍

**Comment by InfiniteCoder** [comment]
@AdiChat  Sure. I'll make a new PR, as this one is riddled with commits. 😆

**Pull request closed without merging**
