### PR TITLE
Karger's min cut algo (C++)

### PR DESCRIPTION
**Pull request by gauravarora011**

### CODE REVIEW

**Comment by gauravarora011** [comment]
Added KRUSKAL's algo as well

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by Vitorvgc** [comment]
About your Kruskal algorithm ([here](https://github.com/OpenGenus/cosmos/blob/master/code/greedy-algorithms/kruskal_minimum_spanning_tree/kruskal.cpp)), I think it is actually written in C. I believe that it would be better to move this to C language, as it wouldn't need any modifications, and open space to a C++ implementation that uses more of the language's features.

**Comment by AdiChat** [comment]
Yes, this is infact written in `C`. Changed in #1077 👍

**Pull request merged**
