### PR TITLE
Create MagicNumber.java

### PR DESCRIPTION
**Pull request by vinayb21**

### CODE REVIEW

**Comment by vinayb21** [comment]
Hi, what are the minimum number of valid pull requests for Hacktober?

**Comment by AdiChat** [comment]
For hacktoberfest, the minimum number is four with no upper limit 😄

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by vinayb21** [comment]
I will contribute as much as I can.

**Pull request merged**
