### PR TITLE
Added Code for NoOfWaysInMaze

### PR DESCRIPTION
**Pull request by sirjan13**
solutio to famous backtracking problem for finding number of paths in a maze

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by sirjan13** [comment]
I am loving it. Can i work on Soduku Checker under Backtracking?

**Comment by AdiChat** [comment]
Sure. Go for it 👍

**Comment by sirjan13** [comment]
Done. #63 . Plz review :)

**Pull request merged**
