### PR TITLE
#3443

### PR DESCRIPTION
**Pull request by notnerb**
**Fixes issue:**
#Algorithm(s)

decision_tree
k_Nearest_Neighbors

File Location :

code/artificial_intelligence/src/decision_tree/decision_tree.py
code/artificial_intelligence/src/k_Nearest_Neighbours/k_Nearest_Neighbours.py

and almost all code using csv file as input

Error :
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

**Changes:**
-minor change of open function call from open(filename, "rt") to open(filename, "rb")

-**also updated syntax to python 3** (I'm not sure this is desired.)

-I can also work over the rest of the affected files, provided there are no criticisms of my commits thus far.

### CODE REVIEW

**Comment by notnerb** [comment]
@tbhaxor Is this what you had in mind?

**Comment by tbhaxor** [comment]
Sorry i didnt get @notnerb

**Comment by AdiChat** [comment]
@tbhaxor: @notnerb meant upgrading to Python 3. :smile:

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus_first

**Pull request merged**
