### PR TITLE
Fixed All Main Folder Names

### PR DESCRIPTION
**Pull request by arnavb**
**Fixes issue:** #2944
**Changes:**
- Fixed main folder names by replacing dashes with underscores.

/cc @AdiChat

(The reason why there are so many files changed is because by changing a folder's name, all the folders/files inside are deleted and readded with the new folder name).

### CODE REVIEW

**Comment by arnavb** [comment]
Is this going to get merged?

**Comment by arnavb** [comment]
@AdiChat Is this going to get merged?

**Comment by AdiChat** [comment]
Yes, I will merge this soon. 👍 

Consistency is important. 👍 
I merged some other pull request after this was opened, so, there might be some files left out.

**Comment by arnavb** [comment]
@AdiChat, these conflicts have been fixed.

**Comment by arnavb** [comment]
Oh great, more conflicts 😞. @AdiChat, I will fix these, but please merge this ASAP, to prevent further conflicts because of other PRs.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by arnavb** [comment]
Thank you @AdiChat!

**Pull request merged**
