### PR TITLE
Java code for bit division

### PR DESCRIPTION
**Pull request by shivanshsoni**

### CODE REVIEW

**Comment by AdiChat** [comment]
Kindly refer to the procedure in [this code in C](https://github.com/OpenGenus/cosmos/blob/master/code/bit-manipulation/bitDivision.c) and make corresponding changes in your code.

It will be good to merge then. 👍

**Comment by shivanshsoni** [comment]
Okk

**Comment by shivanshsoni** [comment]
Done #113

**Comment by AdiChat** [comment]
Looks great 🎉  

Hope you are enjoying your journey with **OpenGenus** 👍

**Pull request merged**
