### PR TITLE
Add Affine cipher algorithm in Java

### PR DESCRIPTION
**Pull request by fuslonflare**
Add Affine cipher algorithm in Java

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by christianbender** [comment]
@fuslonflare @AdiChat  Your cipher program is buggy.
If I encrypt ```"hello"``` with ```a=3``` and ```b=2``` I get ```XOddm```.   
But If I decrypt ```XOddm``` with ```a=3 and b=2``` I get ```HEJJM```.  
I tried to fix it but a don't know.

**Comment by fuslonflare** [comment]
Thank you for your feedback. I will check it back soon.

**Comment by christianbender** [comment]
@fuslonflare I fixed the bug. #3513  Thanks for the feedback.

**Pull request merged**
