### PR TITLE
Correct code

### PR DESCRIPTION
**Pull request by ritwik12**
Missing ";" in some places

**Fixes issue:**
Part of #3594

**Changes:**

Added missing ";" in some places.

### CODE REVIEW

**Comment by ritwik12** [comment]
@arnavb Still, review required?

**Comment by arnavb** [comment]
Oh, I'm not a required reviewer; just wait for @AdiChat!

**Comment by ritwik12** [comment]
@arnavb Sure

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus_nice

**Pull request merged**
