### PR TITLE
Added Python file for Amstrong Number range

### PR DESCRIPTION
**Pull request by shubhajitroy123**
**Fixes issue:**

**Changes:**
Added Python file for Amstrong Number range

### CODE REVIEW

**Review by Aj8620139 — APPROVED** [review]
Hello

**Comment by Aj8620139** [comment]
Hello

**Review by Aj8620139 — APPROVED** [review]

**Review by Aj8620139 — APPROVED** [review]
Hi

**Review by AdiChat — APPROVED** [review]

**Comment by AdiChat** [comment]
Looks great 😍 

Thank you for your contribution.

If you would like to [join our internship program](http://internship.opengenus.org/) and contribute to [OpenGenus IQ](https://iq.opengenus.org/), let us know and we will be happy to have you onboard 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by shubhajitroy123** [comment]
Sure, I would love to join.

**Pull request merged**
