### PR TITLE
SLL, DLL, Trie in JS

### LINKED ISSUE #3655: Add single and double linked lists, trie, javascript implementation
**This is a(n):**

- [x ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Adding both the single and double linked lists in JavaScript, also adding a JavaScript implementation of a trie.

**Discussion**
Would it be beneficial to update the constructor functions in JavaScript structures to ES6 classes?

### PR DESCRIPTION
**Pull request by steven-isbell**
**Fixes issue:**

fixes #3655

**Changes:**

Added a JavaScript implementation of a singly linked list, doubly linked list, and trie data structures.

### CODE REVIEW

**Comment by theodesp** [comment]
Where are the examples?

**Comment by steven-isbell** [comment]
@theodesp Do you mean examples of implementation?

**Comment by steven-isbell** [comment]
@arnavb I've made the changes per your comment

**Comment by arnavb** [comment]
Is the code autoformatted?

**Comment by steven-isbell** [comment]
@arnavb Yep! prettier run over the targeted files.

**Comment by arnavb** [comment]
djldk 3

**Pull request merged**
