### PR TITLE
Fix compile error

### PR DESCRIPTION
**Pull request by iattempt**
**Fixes issue:**
1. #3128 
2. auto test

**Changes:**
1. [x] fix inclusion error
2. [x] fix some typo
3. [x] add tree serializer
~~4. [ ] fix redefinition of the main function~~

[Done]

### CODE REVIEW

**Comment by iattempt** [comment]
@AdiChat please check this error of travis-ci:  0Koci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

**Comment by InfiniteCoder** [comment]
@iattempt  Looks like an issue with Travis to me. Searching online shows that some other projects have had this issue sometimes. I have rebuilt the jobs, and they are building fine now. By the way, looks like you went into beast mode to fix those issues, great 👍

**Comment by iattempt** [comment]
@InfiniteCoder How can I edit compile arguments/flags or contribute the travis-ci?

**Comment by iattempt** [comment]
@AdiChat 
The compile error of the whole files has been fixed, 
but we got the new issue: [multiple definition of `main'].

To fixed that, I have two ideas, which one is better?

1. remove all main of the src files
2. or add a precondition before main function, like:

```c++
#include <vector>
void sort(std::vector<int> arr)
{
    // ...
}

// the precondition we add
#ifdef COSMOS_DEBUG_MODE
// test driver
int main()
{
    // ...
}
#endif //COSMOS_DEBUG_MODE
```

**Comment by InfiniteCoder** [comment]
@iattempt  There are two files, `.travis.yml` contains the configuration for travis builds, such as what compiler to use, what command to run, and so on. It contains the `make c` and `make cpp` commands. These commands refer to the `makefile` file.

I think we'd have to change the way makefile compiles the program. Currently, it finds all the files with .c extention(or .cpp for C++), and compiles them together. Have to see if there is a way to seperately compile each file.

**Comment by iattempt** [comment]
@InfiniteCoder 
Because the files is part lib which will be included to one's project,
I think we still need to 
1. compile the files together,
2. add a main.cpp to be ignore the error: [no main function],
3. and, however, we will compile the test files each.

**Comment by InfiniteCoder** [comment]
I think you should keep seperate PR for travis. Some more changes might be needed for C as well, and clang needs to be fixed or removed as well. This PR has already become too huge 🐘 

Regarding whether the main function should exist or not, I think it depends upon how the programs are meant to be used. If they are to be used as guides/tutorials, then the current method is appropriate. But if they are meant as library, then not only main methods, but also output to stdout should be removed, as replaced with appropriate comments. I think @AdiChat can tell more about this.

**Comment by iattempt** [comment]
No big, I'll revert changes.

**Comment by InfiniteCoder** [comment]
The object files that are giving errors should be deleted. I don't think there is any need for object files in a repo meant for code. Delete them and the build should succeed.

**Comment by iattempt** [comment]
@InfiniteCoder Did you mean the catch_pch.o? but the catch.hpp is too large, I want to save time on compilation.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
