### PR TITLE
Create sumOfDigits.cpp

### PR DESCRIPTION
**Pull request by mjmarrazzo**
Issue #757

### CODE REVIEW

**Comment by mjmarrazzo** [comment]
This is my first pull request, so please let me know if I did anything wrong.

**Comment by AdiChat** [comment]
The code looks good but the `C++` implementation exists. Kindly convert it into `C` code to get this merged 👍

**Comment by arnavb** [comment]
@AdiChat this PR can be closed.

**Comment by AdiChat** [comment]
@mjmarrazzo We have closed this pull request but you can, always, open another pull request for any change anytime. :+1:

**Pull request closed without merging**
