### PR TITLE
File name verification

### PR DESCRIPTION
**Pull request by iendeavor**
**Fixes issue:**
#3371 

**Changes:**

1. Add tool for verify file name

### CODE REVIEW

**Comment by iattempt** [comment]
@AdiChat Please check C++-building before merge PRs.
screen shot 2018-05-23 at 2 04 03 pm

**Comment by arnavb** [comment]
@iendeavor Could you fix the merge conflicts? Then I can approve and merge this.

**Comment by iendeavor** [comment]
@AdiChat 
@arnavb 
I've done my best.

**Comment by iendeavor** [comment]
There is a fatal error which I now can't handle.

There should be exited:

error2

**Comment by arnavb** [comment]
@iendeavor I don't think you need to worry about that; you can always open an issue pointing out the names of these files and their respective errors.

**Comment by arnavb** [comment]
djldk 2

**Pull request merged**
