### PR TITLE
Bubble Sort for C#

### PR DESCRIPTION
**Pull request by ybui210**
Added bubble sort for C#

### CODE REVIEW

**Comment by ybui210** [comment]
Added comment for C# bubble sort

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by Phattraporn** [comment]
ดีค่ะ

**Comment by Phattraporn** [comment]
- [ ] 

@1. 
ซ้ำ Duplicate of 

> 

- **_`[](url)`_**

**Pull request merged**
