### PR TITLE
Added travis CI support

### PR DESCRIPTION
**Pull request by InfiniteCoder**
**Fixes issue:** 
I have added travis ci support. Currently only for C programs

**Changes:**
added .travis.yml
added configure and makefile
renamed some c programs to remove spaces in filenames
added badge to readme

Hopefully, we could add travis build support for all other languages as well. This should provide few main benefits,

1. For now, we can fix issues in existing C programs. Click on the badge in readme and look at the huge list of errors dumped by the compilers(clang and gcc). Contributers --> Fix them.
2. Once this is fixed, no new PR should break the build. We will be able to see beforehand if it does so, and fix it.
3. Maintains quality, and easier for maintainers to maintain the repo.

Do add support for other languages 👍

### CODE REVIEW

**Comment by InfiniteCoder** [comment]
I think @AdiChat , who is the owner of this repo, might have to login to travis and enable the builds. Not sure about this.

**Comment by InfiniteCoder** [comment]
The travis.yml file is not correct right now. Working on fixing it.

**Comment by InfiniteCoder** [comment]
Fixed 😃 . Should build with gcc7 now. Haven't figured out yet how to get both gcc and clang to work with latest versions. But gcc should do fine. 

Do change the badge link later. It currently points to my forked repo, not this one.

**Comment by arnavb** [comment]
You should be able to add support for C++ as well, do you think you can do it?

**Comment by InfiniteCoder** [comment]
I can do it, but I don't want to put everything is single PR

**Comment by InfiniteCoder** [comment]
I have both C and C++ builds ready, both using gcc and clang, thus making a total of 4 builds. You can check them at https://travis-ci.org/InfiniteCoder/cosmos/builds/291524384. I won't add all those commits to this same PR, as they'd be around another 20 commits. I'll make another PR once this is accepted.

**Comment by arnavb** [comment]
Why are you calling make for the C++ builds without a makefile?

**Comment by InfiniteCoder** [comment]
@arnavb The same makefile has two sections(or whatever they call them), one for C and one for C++

**Comment by arnavb** [comment]
@InfiniteCoder My mistake, but you do have an error, since I am looking in the C++ log:

```
make: *** No rule to make target `code/mathematical-algorithms/amicable_numbers/Amicable', needed by `cpp'. Stop.
```

and see this.

**Comment by InfiniteCoder** [comment]
@arnavb That is because filepaths should not have spaces. I fixed that for C, but haven't done for C++ yet.

**Comment by InfiniteCoder** [comment]
Replaced with #2423 . Closing this one.

**Pull request closed without merging**
