### PR TITLE
add: segment tree sum python

### PR DESCRIPTION
**Pull request by abhishekjiitr**
added segment tree for range-sum query and point update, python implementation

### CODE REVIEW

**Comment by abhishekjiitr** [comment]
@AdiChat pls have a look!

**Comment by abhishekjiitr** [comment]
@AdiChat can you merge it ? or are there any issues?

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by abhishekjiitr** [comment]
absolutely!

**Pull request merged**
