### PR TITLE
edit_distance_space_efficient

### PR DESCRIPTION
**Pull request by amankh99**
space efficient version of edit distance with backtracking

### CODE REVIEW

**Comment by AdiChat** [comment]
Kindly remove the files `file1.txt` and `file2.txt` 👍

**Comment by amankh99** [comment]
@AdiChat Please review it and suggest further changes.

**Comment by amankh99** [comment]
@AdiChat Kindly update the status of this pull request so that I can contribute further or I should start working on other contributions to the community. Please guide me.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
