### PR TITLE
remove_duplicates in javascript

### PR DESCRIPTION
**Pull request by tbhaxor**
**Fixes issue:**

**Changes:** Added _Remove Dups_ in `Javascript`

### CODE REVIEW

**Comment by tbhaxor** [comment]
@AdiChat

**Comment by tbhaxor** [comment]
@AdiChat  may i join your organisation ?
---

**Comment by arnavb** [comment]
@tbhaxor Don't repeatedly ping someone, as that may be considered rude. Aditya may not be active right now, and adding to his already large amount of notifications (300-500) is not going to help him too much. Have some patience!

**Comment by tbhaxor** [comment]
my bad @arnavb  i added a new comment, instead of editing the old one  ;_;
my intentions were not to be rude.

**Comment by AdiChat** [comment]
Looks great 😍 

@tbhaxor No problem. I see you are a member now. In case of emergency, you may use [Slack](https://github.com/OpenGenus/OpenGenus-Slack) or [Discourse](https://discourse.opengenus.org/).

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by tbhaxor** [comment]
@AdiChat  i am new to slack i dont know how to signup and join your channel

image

**Pull request merged**
