### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by iattempt**
**Fixes issue:**
#2960 

**Changes:**
add Catch2

### CODE REVIEW

**Comment by arnavb** [comment]
For a second I thought you wrote all 24000 lines of code! 😮

**Comment by AdiChat** [comment]
This is a great addition. A few minor changes and it will be good to be merged 👍 

Kindly rename `Catch2.md` to `readme.md` and remove the `.o` object files.

It looks like the 2 `catch.hpp` files are the same. If it is so, you might remove one. Also, add a `readme.md` at the `test` directory level.

**Comment by iattempt** [comment]
updated,

I was thought the catch.cpp need to store in root/third_party to mention we used it.
and also store in root/tests/c++ to give convenient to coder.😅

I remain tests/c++/build/test_main.cpp.o, because it is pre-compile file, it can reduce compile time.👍

**Comment by AdiChat** [comment]
Looks great 😍 

We can mention the third party libraries by providing a link in the `readme` or prepare a guide 👍 
Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
