### PR TITLE
Add HashTable in Rust

### PR DESCRIPTION
**Pull request by maxtnuk**
**Fixes issue:** #[Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.]

**Changes:**
[Add HashTable in Rust.]

### CODE REVIEW

**Comment by maxtnuk** [comment]
is it pulled?

**Comment by arnavb** [comment]
What's pulled?

**Comment by maxtnuk** [comment]
this Hashtable Rust Code

**Comment by arnavb** [comment]
Could you be more specific, talking in generic words isn't helpful...

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
