### PR TITLE
Armstrong range

### PR DESCRIPTION
**Pull request by SDakshit**
**Changes:** Added necessary code in c for my article, finding all armstrong numbers in a given range.
Link to the article: https://iq.opengenus.org/find-all-armstrong-numbers-in-a-range/

### CODE REVIEW

**Comment by SDakshit** [comment]
@aryan7778 my article and program is about finding the armstrong numbers in a given range. If you enter an appropriate range, you will find 0 included in the list of armstrong numbers.

**Comment by aryan7778** [comment]
@SDakshit I already got that :)
That's why asking you to check again it is not considering 0 in the list as of now.

**Comment by aryan7778** [comment]
@SDakshit  Ohh, sorry I have rechecked the program and found that you are returning armstrong numbers in range (lower_range,upper_range]
I would suggest to include the lower in the range to avoid being confused :)

**Comment by SDakshit** [comment]
@aryan7778 Have a look, I have made the necessary changes :D

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus

**Pull request merged**
