### PR TITLE
Adjacency lists graph representation in C

### PR DESCRIPTION
**Pull request by abdouskamel**
**Changes:**
Hello everybody. I implemented the adjacency lists representation of graphs in C. I saw that there wasn't a specific folder for that, so i added one, and putted my code into it. Hope that helps. :)

### CODE REVIEW

**Comment by abdouskamel** [comment]
I saw that folders were written with dashes, so i did the same. I'll change that.

**Comment by arnavb** [comment]
Make sure you look at the contribution guidelines in the future (located in the Wiki), and look at #2944.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by abdouskamel** [comment]
Thank you, i should have readed it. I have corrected the mistakes in the programming style.

**Pull request merged**
