### PR TITLE
Fenwick Tree

### PR DESCRIPTION
**Pull request by AkshGautam**
Fenwick tree added in cpp and python.

### CODE REVIEW

**Comment by AdiChat** [comment]
Kindly remove the code in C++ and work on code for other task or refactor existing code ([see](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/Fenwick%20Tree/fenwick_tree.cpp))

Move the python code to the `fenwick_tree` folder that exists under the `data_structure` folder. 

I will be good to merge after the above changes 👍

**Comment by AkshGautam** [comment]
Did the required changes. you may merge them now.Thanks

**Comment by AkshGautam** [comment]
Please review the PR #184 @AdiChat

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
