### PR TITLE
Maximum and Minimum of an array using minimum comparisons (Tournament Method)

### PR DESCRIPTION
**Pull request by HariniJeyaraman**
**Fixes issue:**

#4794

**Changes:**

Implemented finding max and min of array using Tournament Method in C++

### CODE REVIEW

**Comment by HariniJeyaraman** [comment]
@arnavb Please review my code

**Comment by HariniJeyaraman** [comment]
@arnavb Please review my code

**Comment by arnavb** [comment]
@HariniJeyaraman Please move your code to the correct directory.

**Comment by HariniJeyaraman** [comment]
@arnavb updated the file path

**Pull request merged**
