### PR TITLE
Create Cohen-SutherlandLineClippingAlgorithm.cpp

### PR DESCRIPTION
**Pull request by piyush26c**
To add Implementation Cohen-SutherlandLineClippingAlgorithm

### CODE REVIEW

**Comment by arnavb** [comment]
@piyush26c Is there any reason you are making multiple pull requests for each change I ask? You should instead just commit to the same branch instead, which reduces clutter.

**Comment by piyush26c** [comment]
No, As I am a newbie to this Github Environment, will take care next time.
Sorry For Inconvenience.

**Comment by arnavb** [comment]
@piyush26c No need to apologize! Just make sure to learn the basics of git and Github before making a PR next time. Trust me, it's must easier through the command line than through the online UI.

**Comment by piyush26c** [comment]
Yeah, I will remove previous PRs.

**Comment by piyush26c** [comment]
May I know why this pull request is not getting merged?
Have I wanted to do some more changes?

**Comment by Vaibhavi24** [comment]
@piyush26c Submit your changes soon!

**Comment by piyush26c** [comment]
As my another pull request on this algorithm had got merged hence i am supposed to close this pull request, right?

**Comment by arnavb** [comment]
@piyush26c Yes.

**Pull request closed without merging**
