### PR TITLE
added program for union and intersection in linked list

### PR DESCRIPTION
**Pull request by ashishkrishan1995**
Added C program to find union and intersection in a linked list

### CODE REVIEW

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by ashishkrishan1995** [comment]
can you please add the Hacktoberfest label :D

**Comment by AdiChat** [comment]
Sure 👍

**Comment by ashishkrishan1995** [comment]
thank you :D

**Pull request merged**
