### PR TITLE
Add Child Process Creation Code in Linux Operating System

### LINKED ISSUE #4009: Add new Algorithm in C for Child Process Creation in Linux Operating System
**This is a(n):**

- [ x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Create and handle Processes in Linux operating system using fork, sleep, wait, exit, getpid, getppid system calls and ps, kill Linux commands.

### PR DESCRIPTION
**Pull request by msknkh**
**Fixes issue:**

Closes #4009

**Changes:**

Added a ProcessCreation Folder in Operating System Folder. It contains implementation in C.

### CODE REVIEW

**Comment by aSquare14** [comment]
I don't know why the tests are failing. @AdiChat could you review this.

**Comment by agzuniverse** [comment]
Hi @msknkh , a few pointers:

* Don't include the code in the Readme. Readme should be used for giving a general explanation of what the program is, what it does, and why it is relevant.
* Are you sure your code is C++, or in C?

The Travis CI build seems to failing on some other files and not the ones you have added in this PR, so don't worry about that.

**Comment by aSquare14** [comment]
> * Are you sure your code is C++, or in C?

I actually tested the code, it runs if you compile it on g++ as well as gcc. But I am not sure what the CI pipeline understands it as. Maybe adding an #include<iostream> would be safer ?

**Comment by msknkh** [comment]
I can change the file extension to C. I think this would work. And also remove the code from README ?

**Comment by arnavb** [comment]
@msknkh While your code is certainly valid C++, you follow common C practices; you should change the extension to `.c`. Also, remove the code from the README, just give a generic overview of the algorithm.

**Comment by aSquare14** [comment]
@msknkh Any updates?

**Comment by msknkh** [comment]
Ma'am @aSquare14, i am having troubles merging my local repository, trying to fix those issues.

**Comment by arnavb** [comment]
djldk

**Pull request merged**
