### PR TITLE
Create CountingNo.OfZeros

### PR DESCRIPTION
**Pull request by edwardrichtofen115**
C++ flie for counting no. of trailing zero's in n!

### CODE REVIEW

**Comment by AdiChat** [comment]
This code in `C++` exists ([see](https://github.com/OpenGenus/cosmos/blob/master/code/mathematical-algorithms/count_trailing_zeroes/count_trailing_zeros_factorial.cpp)) 👍 

Kindly add the `C` code or take a look at other scopes of contribution or refactor existing code 👍

**Comment by edwardrichtofen115** [comment]
Ok. I'll add the c code.

**Comment by edwardrichtofen115** [comment]
Kindly review #685 , the c code

**Comment by AdiChat** [comment]
Merged 👍

**Comment by arnavb** [comment]
@AdiChat Please close!

**Comment by AdiChat** [comment]
@edwardrichtofen115 We have closed this pull request but you can always open another pull request for an addition you wish to make :+1:

**Pull request closed without merging**
