### PR TITLE
Fix travis ci build failure for Job #1893.1

### PR DESCRIPTION
**Pull request by yedhink**
**Fixes issue:**
It fixes the travis ci build error(Job #1893.1) for c-programs. The error was `make: *** No rule to make target code/data_structures/src/list/singly_linked_list/operations/find/finding_if_element_is', needed by 'c'.  Stop.`

**Changes:**
* removed the blank space in the filename of /code/data_structures/src/list/singly_linked_list/operations/find/finding_if_element_is_present_in_the_list.c

### CODE REVIEW

**Comment by arnavb** [comment]
Looks like your two PRs have gotten mixed. Could you close this one and move the changes for this branch into a new branch off master?

**Comment by yedhink** [comment]
@arnavb I didnt quite understand what you mean. I'am currently making a pr from a new branch. Did you mean remove the changes from the other PR and make a pull request from this branch with only the travis build correction code?

**Comment by arnavb** [comment]
Pretty much; this PR also contains your FIFO page replacement algorithm. I only want the Travis fix code in this PR.

**Comment by yedhink** [comment]
@arnavb see if it's okay now. I have removed the changes from FIFO.

**Comment by arnavb** [comment]
djldk 2

**Pull request merged**
