### PR TITLE
Add slow_sort.java

### PR DESCRIPTION
**Pull request by Bobliuuu**
**Changes:**

Added the slow sort algorithm implemented in Java.

### CODE REVIEW

**Comment by AdiChat** [comment]
It seems you pushed an empty file by mistake. You may fix it.

**Comment by Bobliuuu** [comment]
I fixed the file. Please take a look. 

Sorry for the inconvenience.

**Comment by Bobliuuu** [comment]
Hey @AdiChat, I fixed the code for my pull request. Could you take a look?

**Review by AdiChat — APPROVED** [review]

**Comment by AdiChat** [comment]
Looks great 😍 

Thank you for your contribution.

If you would like to [join our internship program](http://internship.opengenus.org/) and contribute to [OpenGenus IQ](https://iq.opengenus.org/), let us know and we will be happy to have you onboard 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
