### PR TITLE
Added Infix to Postfix in c++

### PR DESCRIPTION
**Pull request by Gupta-shifali**
#642 Added Infix to Postfix conversion code in c++

### CODE REVIEW

**Comment by AdiChat** [comment]
The code for infix to postfix already exists in `C++` ([see](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/Stack/infix_to_postfix/infix_to_postfix.cpp)) 👍 

Kindly browse through the code base to find other scopes of contribution or refactor existing code 👍

**Comment by Gupta-shifali** [comment]
Can add a function for postfix evaluation in C++

**Comment by AdiChat** [comment]
Okay. Add the function and will add this as postfix evaluation category 👍

**Comment by AdiChat** [comment]
Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
