### PR TITLE
Add Conway's Game of Life in Ruby

### PR DESCRIPTION
**Pull request by polinadotio**
Reference #1242

### CODE REVIEW

**Comment by polinadotio** [comment]
thanks for the follow up @Vitorvgc. I read through the contribution guidelines, is this the required comment? And does this need to be part of the commit message or just in the PR? 

```
Every code contribution may contain the following comment as a part of it:

/* Part of Cosmos by OpenGenus Foundation */
```

I would also recommend that the maintainers put a link to this https://github.com/OpenGenus/cosmos/wiki/contribute in the README so it's easier for people to find it and read. I originally looked and couldn't find a link to the contribution guidelines. Thanks!

**Comment by Vitorvgc** [comment]
Yes, this is the required comment, and it needs to be presented only in the code.

Thanks for the suggestion @polinadotio, it would be really helpful 👍

**Comment by polinadotio** [comment]
thanks for the clarification, just added it in

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
