### PR TITLE
Armstrong number in php

### PR DESCRIPTION
**Pull request by tbhaxor**

### CODE REVIEW

**Comment by arnavb** [comment]
TOPIC BRANCHES!

**Comment by tbhaxor** [comment]
@arnavb yes

**Comment by arnavb** [comment]
Why are all of your changes in all of your PRs!!!

**Comment by tbhaxor** [comment]
the same thought is coming in my mind 😆

**Comment by arnavb** [comment]
I have a feeling that you either merged everything from your master branch into all of your branches, _or_ you didn't use git checkout where you were supposed to.

**Comment by arnavb** [comment]
I think #2989 is the culprit, since it is coming from the master branch of your fork.

**Comment by tbhaxor** [comment]
😞

**Comment by tbhaxor** [comment]
now what should i do 😕

**Comment by arnavb** [comment]
In each of the individual branches, you may want to revert each change that you don't want, although I am unsure this method will work, since it may revert the changes on all your branches. The only thing I can suggest is to copy all of the changes you made (to a text file, I suppose), and then close all these PRs, and start over, this time making sure you are doing everything properly.

**Pull request closed without merging**
