### PR TITLE
Javascript morse code translator

### PR DESCRIPTION
**Pull request by michaelkrone**
Simple functions for encrypting/decrypting morse codes.

Fix a typo in C++ implementation

### CODE REVIEW

**Comment by michaelkrone** [comment]
#1744

**Comment by AdiChat** [comment]
Morse code in `JS` exists ([see](https://github.com/OpenGenus/cosmos/blob/master/code/cryptography/morse_cipher/morse-code-translator.js)) Kindly make changes to existing code or remove your code 👍 

The typo is good to be merged 👍

**Comment by michaelkrone** [comment]
Oh, I did not have this file in my local branch (cloned an hour ago). Sorry then.

**Comment by AdiChat** [comment]
No problem 👍

**Pull request closed without merging**
