### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by yatharthshahjpr**
I think there were come conflicts with the previous PR  due to which error of branch conflict was coming ...therefore adding a new one !

### CODE REVIEW

**Comment by yatharthshahjpr** [comment]
@AdiChat ,   Please add me !
👍

**Comment by AdiChat** [comment]
Yes, place yourself in sequence. It looks good 👍 

Cheer up. Everyone loves you ❤️ 

_Be positive and find the best in everything_ 👍

**Comment by yatharthshahjpr** [comment]
Thank you so much ! @AdiChat

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by yatharthshahjpr** [comment]
Thank you ! 👍 
Feeling spurred ! :)

**Pull request merged**
