### PR TITLE
dijkstra implementation in java with priority queue

### PR DESCRIPTION
**Pull request by cheikhSall**
**Fixes issue:**
 dijkstra implementation in java with priority queue and some test examples.

**Changes:**
 Added Dijkstra.java in folder  graph_algortihms/src/dijkstra_shortest_path

### CODE REVIEW

**Comment by cheikhSall** [comment]
I agree with you @arnavb . I didn't see the java style guide and I was using the Netbeans 's auto indent. I will make the changes, thanks.

**Comment by arnavb** [comment]
The code still uses spaces. Back to the drawing board! (Google up spaces to tabs converter) 😓

**Comment by cheikhSall** [comment]
I make the conversion on "pinetools" 's website , hope it 's correct.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by cheikhSall** [comment]
of course thanks, I'll add more algorithms or design patterns implementations in a few days.

**Comment by AdiChat** [comment]
Great :smile:

**Pull request merged**
