### PR TITLE
Added New Algorithm for Deletion of nth node in singly Linked List 

### PR DESCRIPTION
**Pull request by Logan-47**
**Fixes issue:**

No issues fixed
New Algorithm added

**Changes:**

New File added at
cosmos/code/data_structures/src/list/singly_linked_list/operations/delete including the algorithm for Deletion of nth node in a Linked List

### CODE REVIEW

**Comment by Logan-47** [comment]
@AdiChat, I have added a new algorithm, will you please take a look at it?

**Comment by AdiChat** [comment]
Nice work :smile: 

I have made a few comments regarding small changes. Do take a look and let me know :+1:

**Comment by Logan-47** [comment]
@AdiChatI have made the required changes  #3599

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
positive_opengenus_first

**Pull request merged**
