### PR TITLE
Updated Hover effect

### PR DESCRIPTION
**Pull request by VkRan**
**Fixes issue:**

**Changes:**

Added hover effect in html/css folder.

### CODE REVIEW

**Review by walidbarakat — CHANGES_REQUESTED** [review]
- please add the line "/* Part of Cosmos by OpenGenus Foundation */" mentioned in [contribute](https://github.com/OpenGenus/cosmos/wiki/contribute) guide.
- remove the unnecessary blank lines - lines number 4 and 12 -, and i think it'd be better to add a new line at the end of the file.

**Comment by VkRan** [comment]
Did the required changes

**Comment by walidbarakat** [comment]
i think it looks ok for me, but we have to wait for another approve

**Review by walidbarakat — APPROVED** [review]

**Comment by VkRan** [comment]
Okay no worries. Just wanted to know that you have to merge this PR, only then it would be counted for my Hacktoberfest challenge, right?

**Comment by walidbarakat** [comment]
i'm not sure if i can do it on my own after another approve of one of the listed [maintainers](https://github.com/OpenGenus/cosmos/wiki/contributors) should do it, but you're right.

**Comment by VkRan** [comment]
Okay thanks for confirming :)

**Review by AdiChat — APPROVED** [review]

**Pull request merged**
