### PR TITLE
ADDED code in Python

### PR DESCRIPTION
**Pull request by darioTecchia**
#1093 Added code in Python

Credits: https://rosettacode.org/wiki/Knapsack_problem/0-1#Python

### CODE REVIEW

**Comment by amartyaamp** [comment]
I see the changes completely same as the rosettacode link given.
Have you tested this ? 
Also, isn't it a better/simpler idea if you assume input as list of weights and values rather than tuple of tuples?

**Comment by darioTecchia** [comment]
Yup, i've tested it and it works. 

Yes, maybe. I can try this solution later.

**Comment by AdiChat** [comment]
We do have array based implementation in other codes. In that sense, this code is good. 
Having other sources is not favourable, but this being your first contribution, it is. 

Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Comment by darioTecchia** [comment]
Oh ok, I understand.

Thanks you!

**Pull request merged**
