### PR TITLE
Binary Indexed Tree (BIT) cpp

### PR DESCRIPTION
**Pull request by DJAcquila**
This is an implementation of a binary indexed tree in cpp. The input is in a readme file

### CODE REVIEW

**Comment by AdiChat** [comment]
Binary tree is same as fenwick tree for which the `C++` code exists ([see](https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/fenwick_tree/fenwick_tree.cpp)) 👍

**Comment by DJAcquila** [comment]
Oh!! Sorry

Em 11/10/2017 12:51, "阿迪亞 查特吉" <notifications@github.com> escreveu:

Binary tree is same as fenwick tree for which the C++ code exists (see
<https://github.com/OpenGenus/cosmos/blob/master/code/data_structures/fenwick_tree/fenwick_tree.cpp>)
👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenGenus/cosmos/pull/1182#issuecomment-335857138>, or mute
the thread

**Comment by AdiChat** [comment]
No problem 👍

**Comment by AdiChat** [comment]
The new addition of segment tree looks great. 

Recently, we updated the structure and classified files into `src` and `test` folders. You should make corresponding changes 👍

**Comment by AdiChat** [comment]
The binary file `.segmentree_rmq.adb.swp` must be removed. It is good to be merged then 👍

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
