### PR TITLE
Added easy exponentation power using gnu ext/numeric. Added modulo power

### PR DESCRIPTION
**Pull request by neckbosov**
this algorithm always implemented in gnu library

### CODE REVIEW

**Comment by arnavb** [comment]
I don't think this will get merged because of the dependency. Is it possible to get the same effect with the `pow()` function from `<cmath>`?

**Comment by neckbosov** [comment]
No, because of floating point errors. I specially write that it is gnu implementation of this algorithm and many programmists use gnu c++ compiler.

**Comment by arnavb** [comment]
Ok, but it is still a dependency, which may prevent it from getting merged.

**Comment by neckbosov** [comment]
@arnavb , ext/numeric is included in gnu c++ standart library, like ext/pb_ds ans bits/stdc++.h. Code with  ext/pb_ds is also merged in cosmos.

**Comment by arnavb** [comment]
Ok, then forget everything I said :/

**Comment by AdiChat** [comment]
Yes, there are 3 other codes that currently use GNU specific dependencies. Merging this in the sense that GNU is pretty much common/ standard even though this will increase a step in our set-up guide 👍

Looks good 👍 

Hope you are enjoying your journey with **OpenGenus**

**Pull request merged**
