### PR TITLE
Codechef RESQ solution in C

### PR DESCRIPTION
**Pull request by ritish099**
**Fixes issue:#4973**

**Changes:**

Added Codechef RESQ solution in C
Added README for Codechef RESQ Problem

### CODE REVIEW

**Comment by ritish099** [comment]
Sir @arnavb ,Check it out

**Comment by ritish099** [comment]
@hanzohasashi33 I saw that you are assigned to some hackerrank code project . Are u a mentor ? or a participant

**Comment by hanzohasashi33** [comment]
I just like to contribute to open source projects like this one.
Not a mentor or participant. @ritish099

**Comment by ritish099** [comment]
Can you Merge my PR ? @hanzohasashi33

**Comment by hanzohasashi33** [comment]
I am not authorized to do so.
@arnavb is the maintainer.
I was told to do code reviews

**Comment by ritish099** [comment]
Ok thanks Sir. @hanzohasashi33

**Pull request merged**
