### PR TITLE
Segregate positive and negative elements of array

### PR DESCRIPTION
**Pull request by HariniJeyaraman**
**Fixes issue:**

 #4734

**Changes:**

 Segregate positive and negative integers in an array in C++

### CODE REVIEW

**Comment by HariniJeyaraman** [comment]
@arnavb Please review the code

**Comment by arnavb** [comment]
Your code is fine, although I would prefer using `std::vector` over a dynamic array. Also why did you delete the other two files?

**Comment by HariniJeyaraman** [comment]
@arnavb I deleted the other files, since I need to use a different branch for each PR. If I hadn't deleted the files, this PR would contain more than 1 file

**Comment by arnavb** [comment]
This PR _does_ contain more that one file. As in, if I merge this, those files will be deleted. Could you clarify what you mean. As of now, I am reluctant to merge this because it will delete those two files.

**Comment by HariniJeyaraman** [comment]
I have these 2 files already in different branches. So, there won't be any problem if this PR gets merged.

**Comment by arnavb** [comment]
@HariniJeyaraman Which two branches? And do they have a PR open? Are you saying that I should merge this in and then those other PRs because they will restore the file? Still unsure what you mean and which two branches/PRs you are referring to.

**Comment by HariniJeyaraman** [comment]
@arnavb so the file unique_number.cpp has already been merged to cosmos through another branch of mine. The other file merge_arrays.cpp has an open PR from a different branch of mine, again. So merging this current PR will not reflect any problems.
For reference these are the PRs
https://github.com/OpenGenus/cosmos/pull/4695

https://github.com/OpenGenus/cosmos/pull/4708

**Pull request merged**
